## BASES POSIBLES

Para clasificación → Bank Marketing.
Para regresión → Online News Popularity.

#### ============================================================ 
#### MARKETING – CLASIFICACIÓN
#### ============================================================

TIPO DE PROBLEMA Clasificación.

PREGUNTA DE INVESTIGACIÓN ¿Qué características de los clientes y de las campañas de marketing permiten predecir si un cliente contratará un depósito a lazo?

OBJETIVO Predecir si un cliente contratará un depósito a plazo luego de una campaña de marketing bancario.

VARIABLE OBJETIVO (y) y

Valores: - yes: el cliente contrató el depósito. - no: el cliente no contrató el depósito.


VARIABLES PREDICTORAS (X) Las restantes variables del dataset, entre
ellas:

-   age: edad del cliente.
-   job: tipo de trabajo.
-   education: nivel educativo.
-   balance: saldo promedio anual.
-   housing: indica si posee préstamo hipotecario.
-   loan: indica si posee préstamo personal.
-   duration: duración del último contacto.
-   campaign: cantidad de contactos realizados durante la campaña.
-   poutcome: resultado de la campaña de marketing anterior.


#### ============================================================ 
#### NEWS POPULARITY – REGRESIÓN
#### ============================================================

TIPO DE PROBLEMA Regresión.

PREGUNTA DE INVESTIGACIÓN: ¿Qué características de una noticia permiten predecir la cantidad de veces que será compartida?


OBJETIVO Predecir la popularidad de una noticia, utilizando como medida
la cantidad de veces que fue compartida.

VARIABLE OBJETIVO (y) shares

VARIABLES PREDICTORAS (X) 
-   n_tokens_title: cantidad de palabras del título.
-   n_tokens_content: cantidad de palabras del contenido.
-   num_self_hrefs: cantidad de enlaces internos.
-   num_imgs: cantidad de imágenes.
-   num_videos: cantidad de videos.
-   num_keywords: cantidad de palabras clave.
-   global_subjectivity: nivel global de subjetividad.
-   global_sentiment_polarity: polaridad global del sentimiento.
-   title_subjectivity: subjetividad del título.
-   title_sentiment_polarity: sentimiento del título.

In [7]:
from ucimlrepo import fetch_ucirepo

In [8]:
## Para clasificación → Bank Marketing.
  
# fetch dataset 
bank_marketing = fetch_ucirepo(id=222) 
  
# data (as pandas dataframes) 
X1 = bank_marketing.data.features 
y1 = bank_marketing.data.targets 
  
# metadata 
print(bank_marketing.metadata) 
  
# variable information 
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

In [9]:
X1.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN

In [10]:
X1.describe()

,age,balance,day_of_week,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [11]:
## Para regresión → Online News Popularity.
  
# fetch dataset 
online_news_popularity = fetch_ucirepo(id=332) 
  
# data (as pandas dataframes) 
X2 = online_news_popularity.data.features 
y2 = online_news_popularity.data.targets 
  
# metadata 
print(online_news_popularity.metadata) 
  
# variable information 
print(online_news_popularity.variables)

{'uci_id': 332, 'name': 'Online News Popularity', 'repository_url': 'https://archive.ics.uci.edu/dataset/332/online+news+popularity', 'data_url': 'https://archive.ics.uci.edu/static/public/332/data.csv', 'abstract': 'This dataset summarizes a heterogeneous set of features about articles published by Mashable in a period of two years. The goal is to predict the number of shares in social networks (popularity).', 'area': 'Business', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 39797, 'num_features': 58, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': [' shares'], 'index_col': ['url'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2015, 'last_updated': 'Thu Feb 15 2024', 'dataset_doi': '10.24432/C5NS3V', 'creators': ['Kelwin Fernandes', 'Pedro Vinagre', 'Paulo Cortez', 'Pedro Sernadela'], 'intro_paper': {'ID': 390, 'type': 'NATIVE', 'title': 'A Proactive Intelligent Decision Support System for Predicting the Popularity of Online News', 'authors': 'Kelwin Fernandes, Pedro Vinagre, P. Cortez', 'venue': 'Portuguese Conference on Artificial Intelligence', 'year': 2015, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/A-Proactive-Intelligent-Decision-Support-System-for-Fernandes-Vinagre/ad7f3da7a5d6a1e18cc5a176f18f52687b912fea', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': '* The articles were published by Mashable (www.mashable.com) and their content as the rights to reproduce it belongs to them. Hence, this dataset does not share the original content but some statistics associated with it. The original content be publicly accessed and retrieved using the provided urls.\r\n* Acquisition date: January 8, 2015\r\n* The estimated relative performance values were estimated by the authors using a Random Forest classifier and a rolling windows as assessment method.  See their article for more details on how the relative performance values were set.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "Number of Attributes: 61 (58 predictive attributes, 2 non-predictive, 1 goal field)\r\n\r\nAttribute Information:\r\n     0. url:                           URL of the article (non-predictive)\r\n     1. timedelta:                     Days between the article publication and the dataset acquisition (non-predictive)\r\n     2. n_tokens_title:                Number of words in the title\r\n     3. n_tokens_content:              Number of words in the content\r\n     4. n_unique_tokens:               Rate of unique words in the content\r\n     5. n_non_stop_words:              Rate of non-stop words in the content\r\n     6. n_non_stop_unique_tokens:      Rate of unique non-stop words in the content\r\n     7. num_hrefs:                     Number of links\r\n     8. num_self_hrefs:                Number of links to other articles published by Mashable\r\n     9. num_imgs:                      Number of images\r\n    10. num_videos:                    Number of videos\r\n    11. average_token_length:          Average length of the words in the content\r\n    12. num_keywords:                  Number of keywords in the metadata\r\n    13. data_channel_is_lifestyle:     Is data channel 'Lifestyle'?\r\n    14. data_channel_is_entertainment: Is data channel 'Entertainment'?\r\n    15. data_channel_is_bus:           Is data channel 'Business'?\r\n    16. data_channel_is_socmed:        Is data channel 'Social Media'?\r\n    17. data_channel_is_tech:          Is data channel 'Tech'?\r\n    18. data_channel_is_world:         Is data channel 'World'?\r\n    19. kw_min_min:                    Worst keyword (min. shares)\r\n    20. kw_max_min:                    Worst keyword (max. shares)\r\n    21. kw_avg_min:                    Worst keyword (avg. shares)\r\n    22. kw_min_max:                    Best keyword (min. shares)\r\n    23. kw_max_max:                    Best keyword (max. shares)\r\n    24. kw_avg_max:                    Best keyword (avg. shares)\r\n    25. kw_min_avg:                    Avg. keyword (min. shares)\r\n    26. kw_max_avg:                    Avg. keyword (max. shares)\r\n    27. kw_avg_avg:                    Avg. keyword (avg. shares)\r\n    28. self_reference_min_shares:     Min. shares of referenced articles in Mashable\r\n    29. self_reference_max_shares:     Max. shares of referenced articles in Mashable\r\n    30. self_reference_avg_sharess:    Avg. shares of referenced articles in Mashable\r\n    31. weekday_is_monday:             Was the article published on a Monday?\r\n    32. weekday_is_tuesday:            Was the article published on a Tuesday?\r\n    33. weekday_is_wednesday:          Was the article published on a Wednesday?\r\n    34. weekday_is_thursday:           Was the article published on a Thursday?\r\n    35. weekday_is_friday:             Was the article published on a Friday?\r\n    36. weekday_is_saturday:           Was the article published on a Saturday?\r\n    37. weekday_is_sunday:             Was the article published on a Sunday?\r\n    38. is_weekend:                    Was the article published on the weekend?\r\n    39. LDA_00:                        Closeness to LDA topic 0\r\n    40. LDA_01:                        Closeness to LDA topic 1\r\n    41. LDA_02:                        Closeness to LDA topic 2\r\n    42. LDA_03:                        Closeness to LDA topic 3\r\n    43. LDA_04:                        Closeness to LDA topic 4\r\n    44. global_subjectivity:           Text subjectivity\r\n    45. global_sentiment_polarity:     Text sentiment polarity\r\n    46. global_rate_positive_words:    Rate of positive words in the content\r\n    47. global_rate_negative_words:    Rate of negative words in the content\r\n    48. rate_positive_words:           Rate of positive words among non-neutral tokens\r\n    49. rate_negative_words:           Rate of negative words among non-neutral tokens\r\n    50. avg_positive_polarity:         Avg. polarity of positive words\r\n    51. min_positive_polarity:         Min. polarity of positive words\r\n    52. max_positive_polarity:         Max. polarity of positive words\r\n    53. avg_negative_polarity:         Avg. polarity of negative  words\r\n    54. min_negative_polarity:         Min. polarity of negative  words\r\n    55. max_negative_polarity:         Max. polarity of negative  words\r\n    56. title_subjectivity:            Title subjectivity\r\n    57. title_sentiment_polarity:      Title polarity\r\n    58. abs_title_subjectivity:        Absolute subjectivity level\r\n    59. abs_title_sentiment_polarity:  Absolute polarity level\r\n    60. shares:                        Number of shares (target)", 'citation': None}}
                             name     role         type demographic  \
0                             url       ID  Categorical        None
1                       timedelta    Other   Continuous        None
2                  n_tokens_title  Feature   Continuous        None
3                n_tokens_content  Feature   Continuous        None
4                 n_unique_tokens  Feature   Continuous        None
..                            ...      ...          ...         ...
56             title_subjectivity  Feature   Continuous        None
57       title_sentiment_polarity  Feature   Continuous        None
58         abs_title_subjectivity  Feature   Continuous        None
59   abs_title_sentiment_polarity  Feature   Continuous        None
60                         shares   Target      Integer        None

   description units missing_values
0         None  None             no
1         None  None             no
2         None  None             no
3         None  None             no
4         None  None             no
..         ...   ...            ...
56        None  None             no
57        None  None             no
58        None  None             no
59        None  None             no
60        None  None             no

[61 rows x 7 columns]

In [12]:
X2.head()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,0.0,4.680365,...,0.378636,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500
1,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,0.0,4.913725,...,0.286915,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000
2,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,0.0,4.393365,...,0.495833,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000
3,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,0.0,4.404896,...,0.385965,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000
4,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,0.0,4.682836,...,0.411127,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364

In [13]:
X2.describe()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,avg_positive_polarity,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,4.548239,...,0.353825,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064
std,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,0.844406,...,0.104542,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000
25%,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,4.478404,...,0.306244,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000
50%,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,4.664082,...,0.358755,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000
75%,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,4.854839,...,0.411428,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000
max,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,8.041534,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000